### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by makhovds** [petronetto/docker-python-deep-learning#11]
Good day!
Could you please help me, I used next comands and get error on the last one
1) docker pull petronetto/docker-python-deep-learning
(it was successfully downloaded)
2) docker run -it --name deep-learning -v $(PWD):/home/notebooks -p 8888:8888 -d petronetto docker-python-deep-learning
Unable to find image 'petronetto:latest' locally
docker: Error response from daemon: pull access denied for petronetto, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

OS is Windows10

**Comment by petronetto** [comment]
Hi, the right command would be:  `docker run -it --name deep-learning -v $(PWD):/home/notebooks -p 8888:8888 -d petronetto/docker-python-deep-learning`, you just missed the `/` between my repo and the container name

**Comment by makhovds** [comment]
Thanks for fast response, now I get:
docker: Error response from daemon: create $(PWD): "$(PWD)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

**Comment by petronetto** [comment]
Dude, `$(PWD)` is a bash command, that basically maps your current directory, if you're using Windows it's obviously that won't work... Just replace it for your current working directory.

**Comment by makhovds** [comment]
My working folder is C:\Users\denni.
I changed working dir in local dockerfile to users\denni, bulded it and ran it.
Now it show me that it is serving all files in \users\denni. But in welcome.ipynb it doesn't know the pytorch and XGBoost, what can be the problem?

**Comment by makhovds** [comment]
Could you please somehow write steps to install your dockfile for windows user?
